image: maven:3.5.3-jdk-10

cache:
  paths:
    - .m2/repository/

stages:
 - build
 - deploy

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
      paths:
        - target/Badge.jar

deploy_staging:
  stage: deploy
  script:
    - mvn heroku:deploy -Dheroku.appName=$HEROKU_APP_STAGING -Dbadge.mode=staging
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - mvn heroku:deploy -Dheroku.appName=$HEROKU_APP_PRODUCTION
  environment:
    name: production
  only:
    - master
