image: maven:3.5.3-jdk-10

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
    # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
    # when running from the command line.
    # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository
    - target/

stages:
 - build
 - deploy


build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
      paths:
        - target/Badge.jar

deploy_staging:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS heroku:deploy -Dheroku.appName=$HEROKU_APP_STAGING -Dbadge.mode=staging
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS heroku:deploy -Dheroku.appName=$HEROKU_APP_PRODUCTION
  environment:
    name: production
  only:
    - master
